variable "equinix_client_id" {}
variable "equinix_client_secret" {}

variable "connection_name" {}
variable "connection_type" {}
variable "notifications_type" {}
variable "notifications_emails" {}
variable "bandwidth" {}
variable "redundancy" {}
variable "purchase_order_number" {}
variable "aside_ap_type" {}
variable "aside_link_protocol_type" {}
variable "aside_link_protocol_stag" {}
variable "zside_ap_type" {}
variable "zside_link_protocol_type" {}
variable "zside_link_protocol_stag" {}
variable "zside_location" {}
variable "aside_port_name" {}
variable "zside_port_name" {}