equinix_client_id     = "MyEquinixClientId"
equinix_client_secret = "MyEquinixSecret"
equinix_port_name     = "EQUINIX_SVC-XXX-CX-PRI-01"
alibaba_account_id    = "1956030"
alibaba_region        = "ap-southeast-2"
alibaba_metro_code    = "SY"
