run:
  modules-download-mode: readonly
  timeout: 10m
linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set

issues:
  max-issues-per-linter: 0
  max-same-issues: 0