run:
  modules-download-mode: readonly
linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - cmd/migration-tool
