run:
  modules-download-mode: readonly
  timeout: 10m
linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - stylecheck
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
