run:
  modules-download-mode: readonly
  skip-dirs:
    - cmd/migration-tool
linters:
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
