equinix_client_id     = "MyEquinixClientId"
equinix_client_secret = "MyEquinixSecret"
equinix_port_name     = "EQUINIX_SVC-XXX-CX-PRI-01"
gcp_region            = "us-west1"
gcp_project_name      = "tf-test"