variable "equinix_client_id" {}
variable "equinix_client_secret" {}

variable "pri_connection_name" {}
variable "sec_connection_name" {}
variable "connection_type" {}
variable "notifications_type" {}
variable "notifications_emails" {}
variable "bandwidth" {}
variable "purchase_order_number" {}
variable "aside_ap_type" {}
variable "aside_link_protocol_type" {}
variable "aside_pri_link_protocol_stag" {}
variable "aside_sec_link_protocol_stag" {}
variable "zside_ap_type" {}
variable "zside_ap_authentication_key" {}
variable "zside_ap_profile_type" {}
variable "zside_location" {}
variable "fabric_sp_name" {}
variable "equinix_pri_port_name" {}
variable "equinix_sec_port_name" {}
