variable "equinix_client_id" {}
variable "equinix_client_secret" {}

variable "fg_name" {}
variable "fg_type" {}
variable "notifications_type" {}
variable "notifications_emails" {}
variable "purchase_order_number" {}
variable "fg_location" {}
variable "fg_package" {}
variable "fg_project" {}
variable "fg_account" {}
variable "connection_name" {}
variable "connection_type" {}
variable "bandwidth" {}
variable "redundancy" {}
variable "aside_ap_type" {}
variable "zside_ap_type" {}
variable "zside_link_protocol_type" {}
variable "zside_link_protocol_tag" {}
variable "zside_location" {}
variable "zside_port_name" {}