variable "equinix_client_id" {}
variable "equinix_client_secret" {}
variable "pri_connection_name" {}
variable "sec_connection_name" {}
variable "connection_type" {}
variable "notifications_type" {}
variable "notifications_emails" {}
variable "bandwidth" {}
variable "pri_purchase_order_number" {}
variable "sec_purchase_order_number" {}
variable "peering_type" {}
variable "aside_ap_type" {}
variable "cloud_router_uuid" {}
variable "zside_ap_type" {}
variable "zside_ap_authentication_key" {}
variable "zside_ap_profile_type" {}
variable "zside_ap_profile_uuid" {}
variable "zside_location" {}
variable "fabric_sp_name" {}