/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// LinkProtocolIpv4Ipv6Config IPv4 or IPv6 specific configuration
type LinkProtocolIpv4Ipv6Config struct {
	// Link subnet prefix
	LinkPrefix *string `json:"linkPrefix,omitempty"`
	// Prefix datatype when linkPrefix not specified
	LocalIfaceIp *string `json:"localIfaceIp,omitempty"`
	// Equinix-side link interface address
	RemoteIfaceIp *string `json:"remoteIfaceIp,omitempty"`
}

// NewLinkProtocolIpv4Ipv6Config instantiates a new LinkProtocolIpv4Ipv6Config object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkProtocolIpv4Ipv6Config() *LinkProtocolIpv4Ipv6Config {
	this := LinkProtocolIpv4Ipv6Config{}
	return &this
}

// NewLinkProtocolIpv4Ipv6ConfigWithDefaults instantiates a new LinkProtocolIpv4Ipv6Config object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkProtocolIpv4Ipv6ConfigWithDefaults() *LinkProtocolIpv4Ipv6Config {
	this := LinkProtocolIpv4Ipv6Config{}
	return &this
}

// GetLinkPrefix returns the LinkPrefix field value if set, zero value otherwise.
func (o *LinkProtocolIpv4Ipv6Config) GetLinkPrefix() string {
	if o == nil || o.LinkPrefix == nil {
		var ret string
		return ret
	}
	return *o.LinkPrefix
}

// GetLinkPrefixOk returns a tuple with the LinkPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkProtocolIpv4Ipv6Config) GetLinkPrefixOk() (*string, bool) {
	if o == nil || o.LinkPrefix == nil {
		return nil, false
	}
	return o.LinkPrefix, true
}

// HasLinkPrefix returns a boolean if a field has been set.
func (o *LinkProtocolIpv4Ipv6Config) HasLinkPrefix() bool {
	if o != nil && o.LinkPrefix != nil {
		return true
	}

	return false
}

// SetLinkPrefix gets a reference to the given string and assigns it to the LinkPrefix field.
func (o *LinkProtocolIpv4Ipv6Config) SetLinkPrefix(v string) {
	o.LinkPrefix = &v
}

// GetLocalIfaceIp returns the LocalIfaceIp field value if set, zero value otherwise.
func (o *LinkProtocolIpv4Ipv6Config) GetLocalIfaceIp() string {
	if o == nil || o.LocalIfaceIp == nil {
		var ret string
		return ret
	}
	return *o.LocalIfaceIp
}

// GetLocalIfaceIpOk returns a tuple with the LocalIfaceIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkProtocolIpv4Ipv6Config) GetLocalIfaceIpOk() (*string, bool) {
	if o == nil || o.LocalIfaceIp == nil {
		return nil, false
	}
	return o.LocalIfaceIp, true
}

// HasLocalIfaceIp returns a boolean if a field has been set.
func (o *LinkProtocolIpv4Ipv6Config) HasLocalIfaceIp() bool {
	if o != nil && o.LocalIfaceIp != nil {
		return true
	}

	return false
}

// SetLocalIfaceIp gets a reference to the given string and assigns it to the LocalIfaceIp field.
func (o *LinkProtocolIpv4Ipv6Config) SetLocalIfaceIp(v string) {
	o.LocalIfaceIp = &v
}

// GetRemoteIfaceIp returns the RemoteIfaceIp field value if set, zero value otherwise.
func (o *LinkProtocolIpv4Ipv6Config) GetRemoteIfaceIp() string {
	if o == nil || o.RemoteIfaceIp == nil {
		var ret string
		return ret
	}
	return *o.RemoteIfaceIp
}

// GetRemoteIfaceIpOk returns a tuple with the RemoteIfaceIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkProtocolIpv4Ipv6Config) GetRemoteIfaceIpOk() (*string, bool) {
	if o == nil || o.RemoteIfaceIp == nil {
		return nil, false
	}
	return o.RemoteIfaceIp, true
}

// HasRemoteIfaceIp returns a boolean if a field has been set.
func (o *LinkProtocolIpv4Ipv6Config) HasRemoteIfaceIp() bool {
	if o != nil && o.RemoteIfaceIp != nil {
		return true
	}

	return false
}

// SetRemoteIfaceIp gets a reference to the given string and assigns it to the RemoteIfaceIp field.
func (o *LinkProtocolIpv4Ipv6Config) SetRemoteIfaceIp(v string) {
	o.RemoteIfaceIp = &v
}

func (o LinkProtocolIpv4Ipv6Config) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LinkPrefix != nil {
		toSerialize["linkPrefix"] = o.LinkPrefix
	}
	if o.LocalIfaceIp != nil {
		toSerialize["localIfaceIp"] = o.LocalIfaceIp
	}
	if o.RemoteIfaceIp != nil {
		toSerialize["remoteIfaceIp"] = o.RemoteIfaceIp
	}
	return json.Marshal(toSerialize)
}

type NullableLinkProtocolIpv4Ipv6Config struct {
	value *LinkProtocolIpv4Ipv6Config
	isSet bool
}

func (v NullableLinkProtocolIpv4Ipv6Config) Get() *LinkProtocolIpv4Ipv6Config {
	return v.value
}

func (v *NullableLinkProtocolIpv4Ipv6Config) Set(val *LinkProtocolIpv4Ipv6Config) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkProtocolIpv4Ipv6Config) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkProtocolIpv4Ipv6Config) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkProtocolIpv4Ipv6Config(val *LinkProtocolIpv4Ipv6Config) *NullableLinkProtocolIpv4Ipv6Config {
	return &NullableLinkProtocolIpv4Ipv6Config{value: val, isSet: true}
}

func (v NullableLinkProtocolIpv4Ipv6Config) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkProtocolIpv4Ipv6Config) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


