/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// ServiceTokenSide Connection link protocol configuration
type ServiceTokenSide struct {
	// List of AccessPointSelectors
	AccessPointSelectors []AccessPointSelector `json:"accessPointSelectors,omitempty"`
}

// NewServiceTokenSide instantiates a new ServiceTokenSide object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceTokenSide() *ServiceTokenSide {
	this := ServiceTokenSide{}
	return &this
}

// NewServiceTokenSideWithDefaults instantiates a new ServiceTokenSide object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceTokenSideWithDefaults() *ServiceTokenSide {
	this := ServiceTokenSide{}
	return &this
}

// GetAccessPointSelectors returns the AccessPointSelectors field value if set, zero value otherwise.
func (o *ServiceTokenSide) GetAccessPointSelectors() []AccessPointSelector {
	if o == nil || o.AccessPointSelectors == nil {
		var ret []AccessPointSelector
		return ret
	}
	return o.AccessPointSelectors
}

// GetAccessPointSelectorsOk returns a tuple with the AccessPointSelectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceTokenSide) GetAccessPointSelectorsOk() ([]AccessPointSelector, bool) {
	if o == nil || o.AccessPointSelectors == nil {
		return nil, false
	}
	return o.AccessPointSelectors, true
}

// HasAccessPointSelectors returns a boolean if a field has been set.
func (o *ServiceTokenSide) HasAccessPointSelectors() bool {
	if o != nil && o.AccessPointSelectors != nil {
		return true
	}

	return false
}

// SetAccessPointSelectors gets a reference to the given []AccessPointSelector and assigns it to the AccessPointSelectors field.
func (o *ServiceTokenSide) SetAccessPointSelectors(v []AccessPointSelector) {
	o.AccessPointSelectors = v
}

func (o ServiceTokenSide) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccessPointSelectors != nil {
		toSerialize["accessPointSelectors"] = o.AccessPointSelectors
	}
	return json.Marshal(toSerialize)
}

type NullableServiceTokenSide struct {
	value *ServiceTokenSide
	isSet bool
}

func (v NullableServiceTokenSide) Get() *ServiceTokenSide {
	return v.value
}

func (v *NullableServiceTokenSide) Set(val *ServiceTokenSide) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceTokenSide) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceTokenSide) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceTokenSide(val *ServiceTokenSide) *NullableServiceTokenSide {
	return &NullableServiceTokenSide{value: val, isSet: true}
}

func (v NullableServiceTokenSide) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceTokenSide) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


