/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2.25
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// Nexus Gateway Access point package data
type NexusGatewayPackage struct {
	// Access point used and maximum number of IPv4 BGP routes
	TotalIPv4RoutesMax int32 `json:"totalIPv4RoutesMax,omitempty"`
	// Access point used and maximum number of IPv6 BGP routes
	TotalIPv6RoutesMax int32 `json:"totalIPv6RoutesMax,omitempty"`
}
