/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// IpBlockPrice IP Block Product configuration
type IpBlockPrice struct {
	// Either uuid or rest of attributes are required
	Uuid *string `json:"uuid,omitempty"`
	Type *IpBlockType `json:"type,omitempty"`
	PrefixLength *int32 `json:"prefixLength,omitempty"`
	Location *PriceLocation `json:"location,omitempty"`
}

// NewIpBlockPrice instantiates a new IpBlockPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpBlockPrice() *IpBlockPrice {
	this := IpBlockPrice{}
	return &this
}

// NewIpBlockPriceWithDefaults instantiates a new IpBlockPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpBlockPriceWithDefaults() *IpBlockPrice {
	this := IpBlockPrice{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *IpBlockPrice) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockPrice) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *IpBlockPrice) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *IpBlockPrice) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IpBlockPrice) GetType() IpBlockType {
	if o == nil || o.Type == nil {
		var ret IpBlockType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockPrice) GetTypeOk() (*IpBlockType, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IpBlockPrice) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given IpBlockType and assigns it to the Type field.
func (o *IpBlockPrice) SetType(v IpBlockType) {
	o.Type = &v
}

// GetPrefixLength returns the PrefixLength field value if set, zero value otherwise.
func (o *IpBlockPrice) GetPrefixLength() int32 {
	if o == nil || o.PrefixLength == nil {
		var ret int32
		return ret
	}
	return *o.PrefixLength
}

// GetPrefixLengthOk returns a tuple with the PrefixLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockPrice) GetPrefixLengthOk() (*int32, bool) {
	if o == nil || o.PrefixLength == nil {
		return nil, false
	}
	return o.PrefixLength, true
}

// HasPrefixLength returns a boolean if a field has been set.
func (o *IpBlockPrice) HasPrefixLength() bool {
	if o != nil && o.PrefixLength != nil {
		return true
	}

	return false
}

// SetPrefixLength gets a reference to the given int32 and assigns it to the PrefixLength field.
func (o *IpBlockPrice) SetPrefixLength(v int32) {
	o.PrefixLength = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *IpBlockPrice) GetLocation() PriceLocation {
	if o == nil || o.Location == nil {
		var ret PriceLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IpBlockPrice) GetLocationOk() (*PriceLocation, bool) {
	if o == nil || o.Location == nil {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *IpBlockPrice) HasLocation() bool {
	if o != nil && o.Location != nil {
		return true
	}

	return false
}

// SetLocation gets a reference to the given PriceLocation and assigns it to the Location field.
func (o *IpBlockPrice) SetLocation(v PriceLocation) {
	o.Location = &v
}

func (o IpBlockPrice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.PrefixLength != nil {
		toSerialize["prefixLength"] = o.PrefixLength
	}
	if o.Location != nil {
		toSerialize["location"] = o.Location
	}
	return json.Marshal(toSerialize)
}

type NullableIpBlockPrice struct {
	value *IpBlockPrice
	isSet bool
}

func (v NullableIpBlockPrice) Get() *IpBlockPrice {
	return v.value
}

func (v *NullableIpBlockPrice) Set(val *IpBlockPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableIpBlockPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableIpBlockPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpBlockPrice(val *IpBlockPrice) *NullableIpBlockPrice {
	return &NullableIpBlockPrice{value: val, isSet: true}
}

func (v NullableIpBlockPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpBlockPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


