/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// PortSortCriteria struct for PortSortCriteria
type PortSortCriteria struct {
	Direction *PortSortDirection `json:"direction,omitempty"`
	Property *PortSortBy `json:"property,omitempty"`
}

// NewPortSortCriteria instantiates a new PortSortCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPortSortCriteria() *PortSortCriteria {
	this := PortSortCriteria{}
	var direction PortSortDirection = DESC
	this.Direction = &direction
	var property PortSortBy = DEVICE_NAME
	this.Property = &property
	return &this
}

// NewPortSortCriteriaWithDefaults instantiates a new PortSortCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPortSortCriteriaWithDefaults() *PortSortCriteria {
	this := PortSortCriteria{}
	var direction PortSortDirection = DESC
	this.Direction = &direction
	var property PortSortBy = DEVICE_NAME
	this.Property = &property
	return &this
}

// GetDirection returns the Direction field value if set, zero value otherwise.
func (o *PortSortCriteria) GetDirection() PortSortDirection {
	if o == nil || o.Direction == nil {
		var ret PortSortDirection
		return ret
	}
	return *o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortSortCriteria) GetDirectionOk() (*PortSortDirection, bool) {
	if o == nil || o.Direction == nil {
		return nil, false
	}
	return o.Direction, true
}

// HasDirection returns a boolean if a field has been set.
func (o *PortSortCriteria) HasDirection() bool {
	if o != nil && o.Direction != nil {
		return true
	}

	return false
}

// SetDirection gets a reference to the given PortSortDirection and assigns it to the Direction field.
func (o *PortSortCriteria) SetDirection(v PortSortDirection) {
	o.Direction = &v
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *PortSortCriteria) GetProperty() PortSortBy {
	if o == nil || o.Property == nil {
		var ret PortSortBy
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PortSortCriteria) GetPropertyOk() (*PortSortBy, bool) {
	if o == nil || o.Property == nil {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *PortSortCriteria) HasProperty() bool {
	if o != nil && o.Property != nil {
		return true
	}

	return false
}

// SetProperty gets a reference to the given PortSortBy and assigns it to the Property field.
func (o *PortSortCriteria) SetProperty(v PortSortBy) {
	o.Property = &v
}

func (o PortSortCriteria) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Direction != nil {
		toSerialize["direction"] = o.Direction
	}
	if o.Property != nil {
		toSerialize["property"] = o.Property
	}
	return json.Marshal(toSerialize)
}

type NullablePortSortCriteria struct {
	value *PortSortCriteria
	isSet bool
}

func (v NullablePortSortCriteria) Get() *PortSortCriteria {
	return v.value
}

func (v *NullablePortSortCriteria) Set(val *PortSortCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullablePortSortCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullablePortSortCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortSortCriteria(val *PortSortCriteria) *NullablePortSortCriteria {
	return &NullablePortSortCriteria{value: val, isSet: true}
}

func (v NullablePortSortCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortSortCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


