/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// VirtualGatewaySortBy : Possible field names to use on sorting
type VirtualGatewaySortBy string

// List of VirtualGatewaySortBy
const (
	NAME_VirtualGatewaySortBy                        VirtualGatewaySortBy = "/name"
	UUID_VirtualGatewaySortBy                        VirtualGatewaySortBy = "/uuid"
	STATE_VirtualGatewaySortBy                       VirtualGatewaySortBy = "/state"
	LOCATIONMETRO_CODE_VirtualGatewaySortBy          VirtualGatewaySortBy = "/location/metroCode"
	LOCATIONMETRO_NAME_VirtualGatewaySortBy          VirtualGatewaySortBy = "/location/metroName"
	PACKAGECODE_VirtualGatewaySortBy                 VirtualGatewaySortBy = "/package/code"
	CHANGE_LOGCREATED_DATE_TIME_VirtualGatewaySortBy VirtualGatewaySortBy = "/changeLog/createdDateTime"
	CHANGE_LOGUPDATED_DATE_TIME_VirtualGatewaySortBy VirtualGatewaySortBy = "/changeLog/updatedDateTime"
)
