/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// RouteTableEntryFilters struct for RouteTableEntryFilters
type RouteTableEntryFilters struct {
	And []RouteTableEntryFilter `json:"and,omitempty"`
}

// NewRouteTableEntryFilters instantiates a new RouteTableEntryFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRouteTableEntryFilters() *RouteTableEntryFilters {
	this := RouteTableEntryFilters{}
	return &this
}

// NewRouteTableEntryFiltersWithDefaults instantiates a new RouteTableEntryFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRouteTableEntryFiltersWithDefaults() *RouteTableEntryFilters {
	this := RouteTableEntryFilters{}
	return &this
}

// GetAnd returns the And field value if set, zero value otherwise.
func (o *RouteTableEntryFilters) GetAnd() []RouteTableEntryFilter {
	if o == nil || o.And == nil {
		var ret []RouteTableEntryFilter
		return ret
	}
	return o.And
}

// GetAndOk returns a tuple with the And field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RouteTableEntryFilters) GetAndOk() ([]RouteTableEntryFilter, bool) {
	if o == nil || o.And == nil {
		return nil, false
	}
	return o.And, true
}

// HasAnd returns a boolean if a field has been set.
func (o *RouteTableEntryFilters) HasAnd() bool {
	if o != nil && o.And != nil {
		return true
	}

	return false
}

// SetAnd gets a reference to the given []RouteTableEntryFilter and assigns it to the And field.
func (o *RouteTableEntryFilters) SetAnd(v []RouteTableEntryFilter) {
	o.And = v
}

func (o RouteTableEntryFilters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.And != nil {
		toSerialize["and"] = o.And
	}
	return json.Marshal(toSerialize)
}

type NullableRouteTableEntryFilters struct {
	value *RouteTableEntryFilters
	isSet bool
}

func (v NullableRouteTableEntryFilters) Get() *RouteTableEntryFilters {
	return v.value
}

func (v *NullableRouteTableEntryFilters) Set(val *RouteTableEntryFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableRouteTableEntryFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableRouteTableEntryFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRouteTableEntryFilters(val *RouteTableEntryFilters) *NullableRouteTableEntryFilters {
	return &NullableRouteTableEntryFilters{value: val, isSet: true}
}

func (v NullableRouteTableEntryFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRouteTableEntryFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


