/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.3
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// VirtualGatewayAccessPointState : Access point lifecycle state
type VirtualGatewayAccessPointState string

// List of VirtualGatewayAccessPointState
const (
	PROVISIONED_VirtualGatewayAccessPointState VirtualGatewayAccessPointState = "PROVISIONED"
	PROVISIONING_VirtualGatewayAccessPointState VirtualGatewayAccessPointState = "PROVISIONING"
	DEPROVISIONING_VirtualGatewayAccessPointState VirtualGatewayAccessPointState = "DEPROVISIONING"
	DEPROVISIONED_VirtualGatewayAccessPointState VirtualGatewayAccessPointState = "DEPROVISIONED"
	LOCKED_VirtualGatewayAccessPointState VirtualGatewayAccessPointState = "LOCKED"
)
