/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// IP Block Product configuration
type IpBlockPrice struct {
	// Either uuid or rest of attributes are required
	Uuid         string         `json:"uuid,omitempty"`
	Type_        *IpBlockType   `json:"type,omitempty"`
	PrefixLength int32          `json:"prefixLength,omitempty"`
	Location     *PriceLocation `json:"location,omitempty"`
}
