/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
	"fmt"
)

// VirtualGatewaySortDirection Sorting direction
type VirtualGatewaySortDirection string

// List of VirtualGatewaySortDirection
const (
	DESC VirtualGatewaySortDirection = "DESC"
	ASC VirtualGatewaySortDirection = "ASC"
)

// All allowed values of VirtualGatewaySortDirection enum
var AllowedVirtualGatewaySortDirectionEnumValues = []VirtualGatewaySortDirection{
	"DESC",
	"ASC",
}

func (v *VirtualGatewaySortDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VirtualGatewaySortDirection(value)
	for _, existing := range AllowedVirtualGatewaySortDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VirtualGatewaySortDirection", value)
}

// NewVirtualGatewaySortDirectionFromValue returns a pointer to a valid VirtualGatewaySortDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVirtualGatewaySortDirectionFromValue(v string) (*VirtualGatewaySortDirection, error) {
	ev := VirtualGatewaySortDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VirtualGatewaySortDirection: valid values are %v", v, AllowedVirtualGatewaySortDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VirtualGatewaySortDirection) IsValid() bool {
	for _, existing := range AllowedVirtualGatewaySortDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to VirtualGatewaySortDirection value
func (v VirtualGatewaySortDirection) Ptr() *VirtualGatewaySortDirection {
	return &v
}

type NullableVirtualGatewaySortDirection struct {
	value *VirtualGatewaySortDirection
	isSet bool
}

func (v NullableVirtualGatewaySortDirection) Get() *VirtualGatewaySortDirection {
	return v.value
}

func (v *NullableVirtualGatewaySortDirection) Set(val *VirtualGatewaySortDirection) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualGatewaySortDirection) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualGatewaySortDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualGatewaySortDirection(val *VirtualGatewaySortDirection) *NullableVirtualGatewaySortDirection {
	return &NullableVirtualGatewaySortDirection{value: val, isSet: true}
}

func (v NullableVirtualGatewaySortDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualGatewaySortDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

