/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
	"fmt"
)

// PortSortBy Possible field names to use on sorting
type PortSortBy string

// List of PortSortBy
const (
	DEVICE_NAME PortSortBy = "/device/name"
)

// All allowed values of PortSortBy enum
var AllowedPortSortByEnumValues = []PortSortBy{
	"/device/name",
}

func (v *PortSortBy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PortSortBy(value)
	for _, existing := range AllowedPortSortByEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PortSortBy", value)
}

// NewPortSortByFromValue returns a pointer to a valid PortSortBy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPortSortByFromValue(v string) (*PortSortBy, error) {
	ev := PortSortBy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PortSortBy: valid values are %v", v, AllowedPortSortByEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PortSortBy) IsValid() bool {
	for _, existing := range AllowedPortSortByEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PortSortBy value
func (v PortSortBy) Ptr() *PortSortBy {
	return &v
}

type NullablePortSortBy struct {
	value *PortSortBy
	isSet bool
}

func (v NullablePortSortBy) Get() *PortSortBy {
	return v.value
}

func (v *NullablePortSortBy) Set(val *PortSortBy) {
	v.value = val
	v.isSet = true
}

func (v NullablePortSortBy) IsSet() bool {
	return v.isSet
}

func (v *NullablePortSortBy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePortSortBy(val *PortSortBy) *NullablePortSortBy {
	return &NullablePortSortBy{value: val, isSet: true}
}

func (v NullablePortSortBy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePortSortBy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

