/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// Actions : Connection action type
type Actions interface{}

// List of Actions
const (
	CONNECTION_CREATION_ACCEPTANCE_Actions     string = "CONNECTION_CREATION_ACCEPTANCE"
	CONNECTION_CREATION_REJECTION_Actions      string = "CONNECTION_CREATION_REJECTION"
	CONNECTION_UPDATE_ACCEPTANCE_Actions       string = "CONNECTION_UPDATE_ACCEPTANCE"
	CONNECTION_UPDATE_REJECTION_Actions        string = "CONNECTION_UPDATE_REJECTION"
	CONNECTION_DELETION_ACCEPTANCE_Actions     string = "CONNECTION_DELETION_ACCEPTANCE"
	CONNECTION_REJECTION_ACCEPTANCE_Actions    string = "CONNECTION_REJECTION_ACCEPTANCE"
	CONNECTION_UPDATE_REQUEST_Actions          string = "CONNECTION_UPDATE_REQUEST"
	MIGRATION_EVPL_VC_Actions                  string = "MIGRATION_EVPL_VC"
	CONNECTION_PROVIDER_STATUS_REQUEST_Actions string = "CONNECTION_PROVIDER_STATUS_REQUEST"
	ACCEPT_HOSTED_CONNECTION_Actions           string = "ACCEPT_HOSTED_CONNECTION"
	CANCEL_EVPL_VC_DRAFT_ORDERS_Actions        string = "CANCEL_EVPL_VC_DRAFT_ORDERS"
)
