/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// PaginationRequest Pagination request information
type PaginationRequest struct {
	// Index of the first element.
	Offset *int32 `json:"offset,omitempty"`
	// Number of elements to be requested per page. Number must be between 1 and 100, and the default is 20.
	Limit *int32 `json:"limit,omitempty"`
}

// NewPaginationRequest instantiates a new PaginationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationRequest() *PaginationRequest {
	this := PaginationRequest{}
	var offset int32 = 0
	this.Offset = &offset
	var limit int32 = 20
	this.Limit = &limit
	return &this
}

// NewPaginationRequestWithDefaults instantiates a new PaginationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationRequestWithDefaults() *PaginationRequest {
	this := PaginationRequest{}
	var offset int32 = 0
	this.Offset = &offset
	var limit int32 = 20
	this.Limit = &limit
	return &this
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *PaginationRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *PaginationRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *PaginationRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *PaginationRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *PaginationRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *PaginationRequest) SetLimit(v int32) {
	o.Limit = &v
}

func (o PaginationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	return json.Marshal(toSerialize)
}

type NullablePaginationRequest struct {
	value *PaginationRequest
	isSet bool
}

func (v NullablePaginationRequest) Get() *PaginationRequest {
	return v.value
}

func (v *NullablePaginationRequest) Set(val *PaginationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationRequest(val *PaginationRequest) *NullablePaginationRequest {
	return &NullablePaginationRequest{value: val, isSet: true}
}

func (v NullablePaginationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


