/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// NexusEquinixStatus : Connection status
type NexusEquinixStatus string

// List of NexusEquinixStatus
const (
	PENDING_DELETE_NexusEquinixStatus                  NexusEquinixStatus = "PENDING_DELETE"
	PROVISIONED_NexusEquinixStatus                     NexusEquinixStatus = "PROVISIONED"
	PENDING_APPROVAL_NexusEquinixStatus                NexusEquinixStatus = "PENDING_APPROVAL"
	NOT_PROVISIONED_NexusEquinixStatus                 NexusEquinixStatus = "NOT_PROVISIONED"
	DEPROVISIONING_NexusEquinixStatus                  NexusEquinixStatus = "DEPROVISIONING"
	NOT_DEPROVISIONED_NexusEquinixStatus               NexusEquinixStatus = "NOT_DEPROVISIONED"
	PENDING_AUTO_APPROVAL_NexusEquinixStatus           NexusEquinixStatus = "PENDING_AUTO_APPROVAL"
	PROVISIONING_NexusEquinixStatus                    NexusEquinixStatus = "PROVISIONING"
	PENDING_BGP_PEERING_NexusEquinixStatus             NexusEquinixStatus = "PENDING_BGP_PEERING"
	PENDING_PROVIDER_VLAN_NexusEquinixStatus           NexusEquinixStatus = "PENDING_PROVIDER_VLAN"
	DEPROVISIONED_NexusEquinixStatus                   NexusEquinixStatus = "DEPROVISIONED"
	PENDING_BANDWIDTH_APPROVAL_NexusEquinixStatus      NexusEquinixStatus = "PENDING_BANDWIDTH_APPROVAL"
	PENDING_PROVIDER_VLAN_ERROR_NexusEquinixStatus     NexusEquinixStatus = "PENDING_PROVIDER_VLAN_ERROR"
	PENDING_INTERFACE_CONFIGURATION_NexusEquinixStatus NexusEquinixStatus = "PENDING_INTERFACE_CONFIGURATION"
)
