/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// ServiceMetro struct for ServiceMetro
type ServiceMetro struct {
	// metro code
	Code *string `json:"code,omitempty"`
	// metro name
	Name *string `json:"name,omitempty"`
	Ibxs []string `json:"ibxs,omitempty"`
	InTrail *bool `json:"inTrail,omitempty"`
	// service metro display name
	DisplayName *string `json:"displayName,omitempty"`
	SellerRegions *map[string]string `json:"sellerRegions,omitempty"`
}

// NewServiceMetro instantiates a new ServiceMetro object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceMetro() *ServiceMetro {
	this := ServiceMetro{}
	return &this
}

// NewServiceMetroWithDefaults instantiates a new ServiceMetro object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceMetroWithDefaults() *ServiceMetro {
	this := ServiceMetro{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ServiceMetro) GetCode() string {
	if o == nil || o.Code == nil {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetCodeOk() (*string, bool) {
	if o == nil || o.Code == nil {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ServiceMetro) HasCode() bool {
	if o != nil && o.Code != nil {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ServiceMetro) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceMetro) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceMetro) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceMetro) SetName(v string) {
	o.Name = &v
}

// GetIbxs returns the Ibxs field value if set, zero value otherwise.
func (o *ServiceMetro) GetIbxs() []string {
	if o == nil || o.Ibxs == nil {
		var ret []string
		return ret
	}
	return o.Ibxs
}

// GetIbxsOk returns a tuple with the Ibxs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetIbxsOk() ([]string, bool) {
	if o == nil || o.Ibxs == nil {
		return nil, false
	}
	return o.Ibxs, true
}

// HasIbxs returns a boolean if a field has been set.
func (o *ServiceMetro) HasIbxs() bool {
	if o != nil && o.Ibxs != nil {
		return true
	}

	return false
}

// SetIbxs gets a reference to the given []string and assigns it to the Ibxs field.
func (o *ServiceMetro) SetIbxs(v []string) {
	o.Ibxs = v
}

// GetInTrail returns the InTrail field value if set, zero value otherwise.
func (o *ServiceMetro) GetInTrail() bool {
	if o == nil || o.InTrail == nil {
		var ret bool
		return ret
	}
	return *o.InTrail
}

// GetInTrailOk returns a tuple with the InTrail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetInTrailOk() (*bool, bool) {
	if o == nil || o.InTrail == nil {
		return nil, false
	}
	return o.InTrail, true
}

// HasInTrail returns a boolean if a field has been set.
func (o *ServiceMetro) HasInTrail() bool {
	if o != nil && o.InTrail != nil {
		return true
	}

	return false
}

// SetInTrail gets a reference to the given bool and assigns it to the InTrail field.
func (o *ServiceMetro) SetInTrail(v bool) {
	o.InTrail = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ServiceMetro) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ServiceMetro) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ServiceMetro) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetSellerRegions returns the SellerRegions field value if set, zero value otherwise.
func (o *ServiceMetro) GetSellerRegions() map[string]string {
	if o == nil || o.SellerRegions == nil {
		var ret map[string]string
		return ret
	}
	return *o.SellerRegions
}

// GetSellerRegionsOk returns a tuple with the SellerRegions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceMetro) GetSellerRegionsOk() (*map[string]string, bool) {
	if o == nil || o.SellerRegions == nil {
		return nil, false
	}
	return o.SellerRegions, true
}

// HasSellerRegions returns a boolean if a field has been set.
func (o *ServiceMetro) HasSellerRegions() bool {
	if o != nil && o.SellerRegions != nil {
		return true
	}

	return false
}

// SetSellerRegions gets a reference to the given map[string]string and assigns it to the SellerRegions field.
func (o *ServiceMetro) SetSellerRegions(v map[string]string) {
	o.SellerRegions = &v
}

func (o ServiceMetro) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Ibxs != nil {
		toSerialize["ibxs"] = o.Ibxs
	}
	if o.InTrail != nil {
		toSerialize["inTrail"] = o.InTrail
	}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.SellerRegions != nil {
		toSerialize["sellerRegions"] = o.SellerRegions
	}
	return json.Marshal(toSerialize)
}

type NullableServiceMetro struct {
	value *ServiceMetro
	isSet bool
}

func (v NullableServiceMetro) Get() *ServiceMetro {
	return v.value
}

func (v *NullableServiceMetro) Set(val *ServiceMetro) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceMetro) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceMetro) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceMetro(val *ServiceMetro) *NullableServiceMetro {
	return &NullableServiceMetro{value: val, isSet: true}
}

func (v NullableServiceMetro) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceMetro) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


