/*
 * Equinix Fabric API v4
 *
 * Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>
 *
 * API version: 4.2.25
 * Contact: api-support@equinix.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package v4

// Colo Access Point
type ServiceProfileAccessPointColo struct {
	SellerRegion            string                             `json:"sellerRegion,omitempty"`
	SellerRegionDescription string                             `json:"sellerRegionDescription,omitempty"`
	CrossConnectId          string                             `json:"crossConnectId,omitempty"`
	Type_                   *ServiceProfileAccessPointTypeEnum `json:"type"`
	Uuid                    string                             `json:"uuid"`
	Location                *SimplifiedLocation                `json:"location,omitempty"`
}
