/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
)

// VirtualGatewayFilters struct for VirtualGatewayFilters
type VirtualGatewayFilters struct {
	And []VirtualGatewayFilter `json:"and,omitempty"`
}

// NewVirtualGatewayFilters instantiates a new VirtualGatewayFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVirtualGatewayFilters() *VirtualGatewayFilters {
	this := VirtualGatewayFilters{}
	return &this
}

// NewVirtualGatewayFiltersWithDefaults instantiates a new VirtualGatewayFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVirtualGatewayFiltersWithDefaults() *VirtualGatewayFilters {
	this := VirtualGatewayFilters{}
	return &this
}

// GetAnd returns the And field value if set, zero value otherwise.
func (o *VirtualGatewayFilters) GetAnd() []VirtualGatewayFilter {
	if o == nil || o.And == nil {
		var ret []VirtualGatewayFilter
		return ret
	}
	return o.And
}

// GetAndOk returns a tuple with the And field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VirtualGatewayFilters) GetAndOk() ([]VirtualGatewayFilter, bool) {
	if o == nil || o.And == nil {
		return nil, false
	}
	return o.And, true
}

// HasAnd returns a boolean if a field has been set.
func (o *VirtualGatewayFilters) HasAnd() bool {
	if o != nil && o.And != nil {
		return true
	}

	return false
}

// SetAnd gets a reference to the given []VirtualGatewayFilter and assigns it to the And field.
func (o *VirtualGatewayFilters) SetAnd(v []VirtualGatewayFilter) {
	o.And = v
}

func (o VirtualGatewayFilters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.And != nil {
		toSerialize["and"] = o.And
	}
	return json.Marshal(toSerialize)
}

type NullableVirtualGatewayFilters struct {
	value *VirtualGatewayFilters
	isSet bool
}

func (v NullableVirtualGatewayFilters) Get() *VirtualGatewayFilters {
	return v.value
}

func (v *NullableVirtualGatewayFilters) Set(val *VirtualGatewayFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableVirtualGatewayFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableVirtualGatewayFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVirtualGatewayFilters(val *VirtualGatewayFilters) *NullableVirtualGatewayFilters {
	return &NullableVirtualGatewayFilters{value: val, isSet: true}
}

func (v NullableVirtualGatewayFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVirtualGatewayFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


