/*
Equinix Fabric API

Equinix Fabric is an advanced software-defined interconnection solution that enables you to directly, securely and dynamically connect to distributed infrastructure and digital ecosystems on platform Equinix via a single port, Customers can use Fabric to connect to: </br> 1. Cloud Service Providers - Clouds, network and other service providers.  </br> 2. Enterprises - Other Equinix customers, vendors and partners.  </br> 3. Myself - Another customer instance deployed at Equinix. </br>

API version: 4.2
Contact: api-support@equinix.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v4

import (
	"encoding/json"
	"fmt"
)

// GatewayActionState Gateway action state
type GatewayActionState string

// List of GatewayActionState
const (
	DONE GatewayActionState = "DONE"
	FAILED GatewayActionState = "FAILED"
	PENDING GatewayActionState = "PENDING"
)

// All allowed values of GatewayActionState enum
var AllowedGatewayActionStateEnumValues = []GatewayActionState{
	"DONE",
	"FAILED",
	"PENDING",
}

func (v *GatewayActionState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GatewayActionState(value)
	for _, existing := range AllowedGatewayActionStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GatewayActionState", value)
}

// NewGatewayActionStateFromValue returns a pointer to a valid GatewayActionState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGatewayActionStateFromValue(v string) (*GatewayActionState, error) {
	ev := GatewayActionState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GatewayActionState: valid values are %v", v, AllowedGatewayActionStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GatewayActionState) IsValid() bool {
	for _, existing := range AllowedGatewayActionStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GatewayActionState value
func (v GatewayActionState) Ptr() *GatewayActionState {
	return &v
}

type NullableGatewayActionState struct {
	value *GatewayActionState
	isSet bool
}

func (v NullableGatewayActionState) Get() *GatewayActionState {
	return v.value
}

func (v *NullableGatewayActionState) Set(val *GatewayActionState) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayActionState) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayActionState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayActionState(val *GatewayActionState) *NullableGatewayActionState {
	return &NullableGatewayActionState{value: val, isSet: true}
}

func (v NullableGatewayActionState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayActionState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

