equinix_client_id     = "MyEquinixClientId"
equinix_client_secret = "MyEquinixSecret"
equinix_port_name     = "EQUINIX_SVC-XXX-CX-PRI-01"
aws_access_key        = "MyAWSAccessKey"
aws_secret_key        = "MyAWSSecretKey"
aws_region            = "us-east-1"
aws_metro_code        = "DC"