variable "equinix_client_id" {}
variable "equinix_client_secret" {}

variable "port_names" {}

variable "name" {}
variable "description" {}
variable "service_profile_type" {}
variable "notifications_type" {}
variable "notifications_emails" {}
variable "tags" {}
variable "visibility" {}
variable "access_point_type_configs_type" {}
variable "access_point_type_configs_connection_redundancy_required" {}
variable "access_point_type_configs_allow_bandwidth_auto_approval" {}
variable "access_point_type_configs_allow_remote_connections" {}
variable "access_point_type_configs_connection_label" {}
variable "access_point_type_configs_enable_auto_generate_service_key" {}
variable "access_point_type_configs_bandwidth_alert_threshold" {}
variable "access_point_type_configs_allow_custom_bandwidth" {}
variable "access_point_type_configs_supported_bandwidths" {}
variable "api_config_api_available" {}
variable "api_config_equinix_managed_vlan" {}
variable "api_config_bandwidth_from_api" {}
variable "api_config_integration_id" {}
variable "api_config_equinix_managed_port" {}
variable "authentication_key_required" {}
variable "authentication_key_label" {}
variable "authentication_key_description" {}
variable "marketing_info_promotion" {}