#!/usr/bin/env bash
set -ux

# This script is a shim to enable re-running failed Terraform
# acceptance tests using gotestsum and producing a separate
# coverage report for each  run of `go test`.  This avoids
# overwriting coverage data from earlier tests in a later run.
# See https://github.com/gotestyourself/gotestsum/issues/274#issuecomment-1321222920

go test -json ./... -coverprofile=coverage.${RANDOM}.txt "$@"