name: Go Tests
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:

  validate_docs:
    name: Validate docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: './go.mod'
        id: go

      - name: Get dependencies
        run: go mod download

      - name: Check that all docs changes are committed
        run: |
          make docs-check

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: './go.mod'
      id: go

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: TF tests
      run: go test -v --coverprofile coverage.txt -covermode=atomic -parallel 4 ./...

    - name: Upload coverage to Codecov
      if: ${{ always() }}
      uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
