equinix_client_id      = "MyEquinixClientId"
equinix_client_secret  = "MyEquinixSecret"
equinix_pri_port_name  = "EQUINIX_SVC-XXX-CX-PRI-01"
equinix_sec_port_name  = "EQUINIX_SVC-XXX-CX-SEC-01"
azure_location         = "West Europe"
azure_peering_location = "Amsterdam"
azure_metro_code       = "AM"
